"""Watchdog-based filesystem monitoring service for TidyOS managed intake roots."""

from __future__ import annotations

import fnmatch
import os
import threading
import time
from pathlib import Path
from typing import Callable, Dict, List, Optional, Set

from watchdog.events import FileSystemEvent, FileSystemEventHandler
from watchdog.observers import Observer

from tidyos.logging_config import get_logger

logger = get_logger("services.watcher")

# Incomplete download / temporary file patterns to strictly ignore
IGNORE_PATTERNS = [
    "*.crdownload",
    "*.part",
    "*.partial",
    "*.tmp",
    "*.temp",
    "~$*",
    ".*",
    "*.lock",
    "*_tidyos_temp*",
]


def should_ignore_file(file_path: str) -> bool:
    """Return True if filename matches temporary, incomplete, or hidden patterns."""
    p = Path(file_path)
    name = p.name.lower()
    for pattern in IGNORE_PATTERNS:
        if fnmatch.fnmatch(name, pattern.lower()):
            return True
    return False


def is_file_stable(file_path: str, wait_seconds: float = 0.6) -> bool:
    """Verify that a file is not actively being written or downloaded.

    Observes file size and mtime over a brief pause to ensure stability.
    """
    p = Path(file_path)
    if not p.exists() or not p.is_file():
        return False

    try:
        s1 = p.stat().st_size
        m1 = p.stat().st_mtime

        # If zero bytes, wait a bit longer to see if write commences
        if s1 == 0:
            time.sleep(wait_seconds * 1.5)
            if not p.exists():
                return False
            s1 = p.stat().st_size
            m1 = p.stat().st_mtime
            if s1 == 0:
                return False

        time.sleep(wait_seconds)
        if not p.exists():
            return False

        s2 = p.stat().st_size
        m2 = p.stat().st_mtime
        return s1 == s2 and m1 == m2
    except Exception as e:
        logger.debug("Stability check exception for '%s': %s", file_path, e)
        return False


class TidyOSEventHandler(FileSystemEventHandler):
    """Custom Watchdog event handler with deduplication and stability checks."""

    def __init__(
        self,
        on_file_detected: Callable[[str], None],
        is_suppressed_callback: Optional[Callable[[str], bool]] = None,
        debounce_seconds: float = 2.0,
    ):
        super().__init__()
        self.on_file_detected = on_file_detected
        self.is_suppressed_callback = is_suppressed_callback
        self.debounce_seconds = debounce_seconds

        # Debounce tracking: {normalized_path: last_event_timestamp}
        self._recent_events: Dict[str, float] = {}
        self._lock = threading.Lock()

    def on_created(self, event: FileSystemEvent):
        if not event.is_directory:
            self._handle_event(event.src_path)

    def on_moved(self, event: FileSystemEvent):
        # When browser renames .crdownload -> final.pdf upon completion
        dest = getattr(event, "dest_path", None)
        if dest and not event.is_directory:
            self._handle_event(dest)

    def _handle_event(self, raw_path: str):
        path_str = str(Path(raw_path).resolve())
        norm_key = path_str.lower()

        # 1. Ignore temporary or lock files
        if should_ignore_file(path_str):
            logger.debug("Ignoring temporary file: %s", path_str)
            return

        # 2. Check if event was generated by TidyOS's own MutationService
        if self.is_suppressed_callback and self.is_suppressed_callback(path_str):
            logger.debug("Suppressing TidyOS-generated filesystem event: %s", path_str)
            return

        # 3. Debounce rapid duplicate events
        now = time.time()
        with self._lock:
            last_time = self._recent_events.get(norm_key, 0.0)
            if now - last_time < self.debounce_seconds:
                return
            self._recent_events[norm_key] = now

        # 4. Asynchronous stability verification and dispatch
        thread = threading.Thread(
            target=self._verify_and_dispatch,
            args=(path_str,),
            daemon=True,
            name=f"WatcherStable-{Path(path_str).name}",
        )
        thread.start()

    def _verify_and_dispatch(self, file_path: str):
        """Wait for file stability, then invoke the pipeline callback."""
        if not is_file_stable(file_path):
            logger.debug("File '%s' not stable or disappeared; skipping", file_path)
            return

        logger.info("New stable file detected: %s", file_path)
        try:
            self.on_file_detected(file_path)
        except Exception as e:
            logger.error("Error in on_file_detected callback for '%s': %s", file_path, e, exc_info=True)


class FilesystemWatcher:
    """Manages active filesystem observer across approved intake folders."""

    def __init__(
        self,
        on_file_detected: Callable[[str], None],
        is_suppressed_callback: Optional[Callable[[str], bool]] = None,
        debounce_seconds: float = 2.0,
    ):
        self.on_file_detected = on_file_detected
        self.is_suppressed_callback = is_suppressed_callback
        self.debounce_seconds = debounce_seconds

        self._observer: Optional[Observer] = None
        self._watched_roots: Set[str] = set()
        self._is_running = False
        self._lock = threading.Lock()

    @property
    def is_running(self) -> bool:
        return self._is_running

    def start(self, roots_to_watch: List[str]):
        """Start monitoring the specified approved folders."""
        with self._lock:
            if self._is_running:
                self.stop()

            self._observer = Observer()
            handler = TidyOSEventHandler(
                on_file_detected=self.on_file_detected,
                is_suppressed_callback=self.is_suppressed_callback,
                debounce_seconds=self.debounce_seconds,
            )

            self._watched_roots.clear()
            for root_str in roots_to_watch:
                rp = Path(root_str)
                if rp.exists() and rp.is_dir():
                    try:
                        self._observer.schedule(handler, str(rp), recursive=True)
                        self._watched_roots.add(str(rp.resolve()))
                        logger.info("Watching approved folder: %s", rp)
                    except Exception as e:
                        logger.warning("Could not watch directory '%s': %s", rp, e)

            if self._watched_roots:
                self._observer.start()
                self._is_running = True
                logger.info("FilesystemWatcher started with %d roots.", len(self._watched_roots))
            else:
                logger.warning("No valid roots found to watch.")

    def stop(self):
        """Stop filesystem monitoring."""
        with self._lock:
            if self._observer and self._is_running:
                try:
                    self._observer.stop()
                    self._observer.join(timeout=3.0)
                except Exception as e:
                    logger.debug("Error stopping observer: %s", e)
                finally:
                    self._observer = None
                    self._is_running = False
                    self._watched_roots.clear()
                    logger.info("FilesystemWatcher stopped.")
